export const PRESETS = [
  {
    id: "all-off",
    label: "All Off",
    desc: "Zero LEDs, stop motors, sound 0",
    data: {
      circleLEDs: Array(8).fill(0),
      frontLegoLEDs: Array(8).fill(0),
      rearLegoLEDs: Array(8).fill(0),
      flRGB: { r: 0, g: 0, b: 0 },
      frRGB: { r: 0, g: 0, b: 0 },
      blRGB: { r: 0, g: 0, b: 0 },
      brRGB: { r: 0, g: 0, b: 0 },
      motorLeft: 0,
      motorRight: 0,
      sound: 0,
      smallBottomRGB: { r: 0, g: 0, b: 0 },
      smallBackRGB: { r: 0, g: 0, b: 0 },
      buttonLEDS: Array(4).fill(0),
      receiverLED: 0,
      microphoneLED: false,
    },
  },
  {
    id: "headlights",
    label: "Headlights",
    desc: "Front RGB bright white, motors stopped",
    data: {
      flRGB: { r: 15, g: 15, b: 15 },
      frRGB: { r: 15, g: 15, b: 15 },
      blRGB: { r: 0, g: 0, b: 0 },
      brRGB: { r: 0, g: 0, b: 0 },
      motorLeft: 0,
      motorRight: 0,
      sound: 0,
    },
  },
  {
    id: "brake-lights",
    label: "Brake Lights",
    desc: "Rear RGB red, motors stopped",
    data: {
      flRGB: { r: 0, g: 0, b: 0 },
      frRGB: { r: 0, g: 0, b: 0 },
      blRGB: { r: 15, g: 0, b: 0 },
      brRGB: { r: 15, g: 0, b: 0 },
      motorLeft: 0,
      motorRight: 0,
      sound: 0,
    },
  },
  {
    id: "spin",
    label: "Spin In Place",
    desc: "Motors opposite, blue corners",
    data: {
      flRGB: { r: 0, g: 0, b: 15 },
      frRGB: { r: 0, g: 0, b: 15 },
      blRGB: { r: 0, g: 0, b: 15 },
      brRGB: { r: 0, g: 0, b: 15 },
      motorLeft: 250,
      motorRight: -250,
      sound: 0,
    },
  },
  {
    id: "forward",
    label: "Forward",
    desc: "Motors forward, circle LEDs mid",
    data: {
      circleLEDs: Array(8).fill(8),
      motorLeft: 300,
      motorRight: 300,
      sound: 0,
    },
  },
  {
    id: "alert",
    label: "Alert",
    desc: "All LEDs high + sound",
    data: {
      circleLEDs: Array(8).fill(15),
      frontLegoLEDs: Array(8).fill(15),
      rearLegoLEDs: Array(8).fill(15),
      flRGB: { r: 15, g: 0, b: 0 },
      frRGB: { r: 15, g: 0, b: 0 },
      blRGB: { r: 15, g: 0, b: 0 },
      brRGB: { r: 15, g: 0, b: 0 },
      motorLeft: 0,
      motorRight: 0,
      sound: 10,
      smallBottomRGB: { r: 15, g: 0, b: 0 },
      smallBackRGB: { r: 15, g: 0, b: 0 },
      buttonLEDS: Array(4).fill(15),
      receiverLED: 15,
      microphoneLED: true,
    },
  },
];
